# Generated by Django 4.2.13 on 2026-02-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msapp', '0003_watchedmovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='is_tv',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
