# Generated by Django 4.2.13 on 2026-02-17 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msapp', '0004_alter_movie_is_tv_alter_movie_release_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msapp.movie')),
                ('movies_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msapp.movieslist')),
            ],
            options={
                'unique_together': {('movies_list', 'movie')},
            },
        ),
    ]
