# Generated by Django 4.2.13 on 2026-02-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msapp', '0005_movielistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieslist',
            name='movies',
            field=models.ManyToManyField(related_name='movies_lists', through='msapp.MovieListItem', to='msapp.movie'),
        ),
    ]
