# Generated by Django 4.2.13 on 2026-02-17 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msapp', '0006_alter_movieslist_movies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movielistitem',
            options={'ordering': ['-added_at']},
        ),
        migrations.AlterField(
            model_name='movielistitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='movielistitem',
            name='movies_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='msapp.movieslist'),
        ),
    ]
