# Generated by Django 4.2.13 on 2026-09-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msapp', '0007_alter_movielistitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
