# Generated by Django 4.2.13 on 2026-09-18 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msapp', '0008_movie_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieslist',
            name='is_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movieslist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
