# Generated by Django 4.2.13 on 2026-09-18 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msapp', '0009_movieslist_fk_and_is_collection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchedmovie',
            unique_together=set(),
        ),
    ]
