# Generated by Django 4.2.13 on 2026-09-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msapp', '0010_remove_watchedmovie_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieslist',
            name='icon',
            field=models.CharField(default='🎬', max_length=10),
        ),
    ]
