# Generated by Django 4.2.13 on 2026-09-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msapp', '0011_add_movieslist_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movielistitem',
            options={'ordering': ['position', '-added_at']},
        ),
        migrations.AddField(
            model_name='movielistitem',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
