# Generated by Django 4.2.13 on 2026-09-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msapp', '0012_add_movielistitem_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='vote_average',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
