# Generated by Django 4.2.13 on 2026-09-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msapp', '0015_movierecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='accepted_notified',
            field=models.BooleanField(default=False),
        ),
    ]
