# Generated by Django 4.2.13 on 2026-09-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msapp', '0016_friendship_accepted_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierecommendation',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
